name: CI Build and Test

on: [push]

jobs:
  linux-build:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List workspace contents
      run: ls -la ${{ github.workspace }}
    
    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build project
      run: cmake --build build --config Release --parallel 2
    
    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure
    
    - name: Run hello executable
      working-directory: ./build/hello_world_application
      run: ./hello

  windows-build:
    name: Build and Test on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List workspace contents
      run: dir ${{ github.workspace }}
    
    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build project
      run: cmake --build build --config Release
    
    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure
    
    - name: Run hello executable
      working-directory: ./build/hello_world_application/Release
      run: .\hello.exe
