name: Linux CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    
    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang

    - name: Сборка CMake
      run: |
        mkdir -p build
        cmake -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

    - name: Build
      run: |
        cmake --build build -- -j $(nproc)

    - name: Тесты
      working-directory: ./build
      run: ctest --output-on-failure