name: Windows CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Проверка кода
      uses: actions/checkout@v4
      
    - name: Установка MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Установка CMake
      uses: actions/setup-cmake@v3
      
    - name: Конфигурация CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ..
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel 4
        
    - name: Verify build output
      run: |
        echo "Checking build directory structure..."
        ls -R build
        
        if (Test-Path "build/hello_world_application/Release/hello_world.exe") {
          echo "hello_world.exe found"
        } else {
          echo "ERROR: hello_world.exe not found!"
          Get-ChildItem -Path build -Recurse -Filter *.exe | ForEach-Object { echo "Found: $($_.FullName)" }
          exit 1
        }
        
        if (Test-Path "build/solver_application/Release/solver.exe") {
          echo "solver.exe found"
        } else {
          echo "ERROR: solver.exe not found!"
          exit 1
        }
      
    - name: Run tests
      run: |
        echo "Current directory: $(Get-Location)"
        echo "Running hello_world:"
        Start-Process -FilePath "build/hello_world_application/Release/hello_world.exe" -Wait -NoNewWindow
        
        echo "Running solver:"
        Start-Process -FilePath "build/solver_application/Release/solver.exe" -Wait -NoNewWindow
        
        echo "All tests executed successfully"