name: Windows CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Проверка кода
      uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    
    - name: Установка CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
      
    - name: Конфигурация CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ..
        
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --parallel 4
    
    - name: Проерка Build
      run: |
        echo "Checking build directory structure..."
        ls -R build
      
        if (Test-Path "build/Release/hello_world_application/hello.exe") {
          echo "hello.exe found"
        } else {
          echo "ERROR: hello.exe not found!"
          Get-ChildItem -Path build -Recurse -Filter *.exe | ForEach-Object { echo "Found: $($_.FullName)" }
          exit 1
        }
      
        if (Test-Path "build/Release/solver_application/solver.exe") {
          echo "solver.exe found"
        } else {
         echo "ERROR: solver.exe not found!"
         exit 1
        }
        
      
    - name: Run tests
      run: |
        cd build/Release
        .\hello_world_application\hello.exe
        .\solver_application\solver.exe