name: Windows CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Устновка CMake
      uses: actions/setup-cmake@v3

    - name: Конфигурация CMake
      run: |
        mkdir build
        cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Run tests
      working-directory: ./build/Release
      run: |
        .\hello_world_application\hello.exe
        .\solver_application\solver.exe